name: test project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.1
    - name: Install Node JS
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install ${{ github.workspace }}/code/02-finished/package.json
    - name: Run tests
      run: npm test ${{ github.workspace }}/code/02-finished/package.json
        
  
